### ISSUE TITLE
Issues in forms

### ISSUE THREAD

**Issue by debnathsubhradip** [Cubefrost-Org/sea-manifesto#25]
There are some issues in ArrivalManifestAmmendment.java, DepartureManifestAmmendment.java which I cannot trace out.
On running those files the below error is getting generated. Please look into this @Nibba2018 
`Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: invalid range properties
	at java.desktop/javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:109)
	at java.desktop/javax.swing.JSlider.<init>(JSlider.java:278)
	at java.desktop/javax.swing.JSlider.<init>(JSlider.java:223)
	at seamanifesto.DepartureManifestAmmendment.generateFields(DepartureManifestAmmendment.java:97)
	at seamanifesto.DepartureManifestAmmendment.generateFields(DepartureManifestAmmendment.java:121)
	at seamanifesto.DepartureManifestAmmendment.generateFields(DepartureManifestAmmendment.java:121)
	at seamanifesto.DepartureManifestAmmendment.generateForm(DepartureManifestAmmendment.java:142)
	at seamanifesto.DepartureManifestAmmendment.<init>(DepartureManifestAmmendment.java:42)
	at seamanifesto.DepartureManifestAmmendment$3.run(DepartureManifestAmmendment.java:269)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by debnathsubhradip** [comment]
![image](https://user-images.githubusercontent.com/55998047/110211744-05bb9e80-7ebe-11eb-9a75-e4b14b56a30f.png)
here's the image of the error
